apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: cafe
spec:
  hostnames:
  - "cafe.example.com"
  rules:
  - backendRefs:
    - name: main
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: coffee
spec:
  hostnames:
  - "cafe.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /coffee
      method: GET
      headers:
        - name: X-Demo-Header # header names and values are case-insensitive
          value: Demo-X1
        - name: version
          value: v1
      queryParams:
        - name: Great # query params and values are case-sensitive
          value: Example
    backendRefs:
    - name: coffee
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: tea
spec:
  hostnames:
  - "cafe.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /tea
    backendRefs:
    - name: tea
      port: 80
